// services/desktop-render/src/App.tsx
import { FunctionComponent, useEffect, useState } from 'react';
import { Button, World } from '@white-rabbit/components';

const { ipcRenderer } = window.require('electron');

const App: FunctionComponent = () => {
  const [user, setUser] = useState<string>('null');
  useEffect(() => {
    ipcRenderer.invoke('business-logic').then((result: string) => setUser(result));
  }, []);

  return (
    <>
      <div>
        Chrome Version:
        <span id="chrome-version" />
      </div>
      <div>
        Electron Version:
        <span id="electron-version" />
      </div>
      <div>
        Node Version:
        <span id="node-version" />
      </div>
      <Button />
      <World />
      <pre>{user}</pre>
    </>
  );
};

export default App;

// packages/desktop-render/src/App.vue
<template>
  <Hello></Hello>
  <World></World>
  <button @click="loadBusinessLogic">Load business logic</button>
  <code>
    <pre>{{ result }}</pre>
  </code>
</template>

<script setup lang="ts">
import { Hello, World } from "@white-rabbit/components";
import { ref } from "vue";

const result = ref("");

const loadBusinessLogic = () =>
  window.ipcRenderer
    .invoke("business-logic")
    .then((r: string) => (result.value = r));
</script>

<style scoped></style>
